name: Sync SCSS to wjst-css

on:
  push:
    paths:
      - 'template/css/scss/**' # Trigger only on changes in the scss folder

jobs:
  sync-scss:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repository
      uses: actions/checkout@v3

    - name: Set up SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Sync SCSS folder to wjst-css
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git clone git@github.com:WebArtWork/wjst-css.git wjst-css
        rm -rf wjst-css/*
        cp -r template/css/scss/* wjst-css/
        cd wjst-css
        git add .
        git commit -m "Update SCSS files from source repository" || echo "No changes to commit"
        git push --force

    - name: Clean up SSH
      run: |
        rm -f ~/.ssh/id_rsa
        rm -f ~/.ssh/known_hosts
